[package]
name = "squirrel-rs"
version = "0.1.0"
authors = ["sim82 <simberger@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
byteorder = "1"
